name: Delete Cache after PR merge

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  actions: write

jobs:
  cleanup:
    name: Clear cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}

          # get the branch
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          # fetch list of cache key
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          # set this to not fail the workflow while deleting cache keys
          set +e

          # delete cache key
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cancel Workflow Runs
        uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
        with:
          all_but_latest: false
          workflow_id: cicd.yml
